// Generates 4:5 WebP variants for every photo in image-src/officerpics.
// Output: public/assets/officerpics/<name>-300.webp and <name>-600.webp. These are
// gitignored and regenerated by `npm run dev` / `npm run build`; data files reference
// them as photo: "/assets/officerpics/<name>". Only missing or stale outputs are rebuilt,
// and outputs whose source photo was removed are deleted.
import sharp from "sharp";
import { mkdir, readdir, rename, rm, stat } from "node:fs/promises";
import path from "node:path";

const SRC = "image-src/officerpics";
const OUT = "public/assets/officerpics";
const WIDTHS = [300, 600];
const RATIO = 5 / 4;

const mtime = (p) => stat(p).then((s) => s.mtimeMs, () => 0);

await mkdir(OUT, { recursive: true });
const files = (await readdir(SRC)).filter((f) => /\.(jpe?g|png|webp|avif|tiff?)$/i.test(f));

const seen = new Set();
let generated = 0;
for (const file of files) {
  const base = path.parse(file).name.toLowerCase();
  if (seen.has(base)) throw new Error(`Duplicate photo name: ${base}`);
  seen.add(base);

  const src = path.join(SRC, file);
  const srcTime = await mtime(src);
  for (const w of WIDTHS) {
    const out = path.join(OUT, `${base}-${w}.webp`);
    if ((await mtime(out)) > srcTime) continue;
    const info = await sharp(src)
      .rotate()
      .resize({
        width: w,
        height: Math.round(w * RATIO),
        fit: "cover",
        position: sharp.strategy.attention,
        withoutEnlargement: true,
      })
      .webp({ quality: 80 })
      .toFile(`${out}.tmp`);
    await rename(`${out}.tmp`, out);
    generated++;
    console.log(`${out}  ${info.width}x${info.height}  ${(info.size / 1024).toFixed(0)} KB`);
  }
}

for (const f of await readdir(OUT)) {
  const m = f.match(/^(.+)-\d+\.webp$/);
  if (m && !seen.has(m[1])) {
    await rm(path.join(OUT, f));
    console.log(`removed orphan ${f}`);
  }
}
console.log(`${generated} generated, ${files.length * WIDTHS.length - generated} up to date`);
